### PR TITLE
Several build fixes

### PR DESCRIPTION
**Pull request by severin-lemaignan**
It took me 2 days, but I've been eventually able to build V4R on my machine :-) Not that bad, considering the breadth the project and its WIP status!

The changes are mostly CMake related. The build was performed on Ubuntu 15.10 (with GCC 5.2 -- I've attempted to use clang as well, but it did not turn well due to [C++11 ABI changes](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html) that makes it hard to link clang-generated code with GCC-compiled system libraries).

The only component I have not been able to build is ObjectGroundTruthAnnotator. The reason is:
- ObjectGroundTruthAnnotator requires VTK
- I need to use vtk 5, due to libpcl-dev still requiring vtk5 (fixing in Debian upstream, though)
- vtk6 and vtk5 packages are mutually exclusive
- vtk5 needs qt4
- I've been using qt5 everywhere else, and I did not feel adding support for both qt4 and qt5 in `FindQT.cmake` (although it would be theoretically possible)

For reference, my build configuration:

```
--   V4R modules:
--     To be built:                 core io common features keypoints ml reconstruction registration rendering segmentation tracking object_modelling recognition
--     Disabled:                    -
--     Disabled by dependency:      -
--     Unavailable:                 -
-- 
--   GUI: 
--     QT 5.x:                      YES (ver 5.4.2)
--     QT OpenGL support:           YES (Qt5::OpenGL 5.4.2)
--     OpenGL support:              YES (/usr/lib/x86_64-linux-gnu/libGLU.so /usr/lib/x86_64-linux-gnu/libGL.so)
--     VTK support:                 NO
-- 
--   Media I/O: 
--     ZLib:                        (ver )
--     JPEG:                        NO
--     WEBP:                        NO
--     PNG:                         build (ver )
--     TIFF:                        NO
--     JPEG 2000:                   NO
--     OpenEXR:                     NO
--     EDT:                         build (ver )
--     SiftGPU:                     build (ver v400)
--     METSlib:                     build (ver 0.5.3)
--     LIBSVM:                      build (ver 3.20)
--     PCL:                         YES (ver 1.7.2)
--     QT:                          YES (ver 5.4.2)
--     OpenCV:                      YES (ver 2.4.9)
--     OpenNI2:                     YES (ver 2.2.0.3)
--     Ceres:                       YES (ver 1.12.0)
--     OPENGL:                      YES
--     Assimp:                      /usr/lib/libassimp.so (ver 3.0.1264)
--     GDAL:                        NO
--     GLOG:                        /usr/lib/x86_64-linux-gnu/libglog.so
-- 
--   Video I/O:
--     OpenNI:                      NO
--     OpenNI2:                     YES (ver 2.2.0.3)
--     PvAPI:                       NO
--     GigEVisionSDK:               NO
-- 
--   Parallel framework:            OpenMP
-- 
--   Other third-party libraries:
--     Use Eigen:                   YES (ver 3.2.5)
--     Use GLM:                     YES (ver 0.9.6)
--     Use Cuda:                    YES (ver 7.5)
--     Use OpenCL:                  NO
--     Use GLEW:                    YES
-- 
--   NVIDIA CUDA
--     Use CUFFT:                   YES
--     Use CUBLAS:                  NO
--     USE NVCUVID:                 NO
--     NVIDIA GPU arch:             11 12 13 20 21 30 35
--     NVIDIA PTX archs:            30
--     Use fast math:               NO
-- 
--   Documentation:
--     Doxygen:                     /usr/bin/doxygen (ver 1.8.9.1)
-- 
--   Tests and samples:
--     Tests:                       NO
--     Performance tests:           NO
--     C/C++ Examples:              YES
-- 
--   Install path:                  /home/slemaignan/dev
```

Now, let's play with V4R :-)

### CODE REVIEW

**Comment by taketwo** [comment]
LGTM

**Comment by ToMadoRe** [comment]
First of all, thanks for contributing and testing the V4R library. Overall the pull request looks okay but Jenkins still failed to build. Two reason for this are: 
* WITH_QT is turned off by default (https://github.com/severin-lemaignan/v4r/blob/build-fixes/CMakeLists.txt#L99)
* Qt4 wraps the files in `${HEADERS}` and `${FORMS}` before this list is actually defined https://github.com/severin-lemaignan/v4r/blob/build-fixes/apps/RTMT/CMakeLists.txt#L62

Could you please update your pull request with these changes so we can try again?

**Comment by severin-lemaignan** [comment]
@ToMadoRe do you mean you want me to enable WITH_QT by default? (it was originally OFF by default -- but WITH_QT4 was on by default, which is a bit inconsistent...)

**Comment by ToMadoRe** [comment]
@severin-lemaignan The problem is at https://github.com/severin-lemaignan/v4r/blob/build-fixes/cmake/V4RFindQt.cmake#L1if WITH_QT is disabled but WITH_QT4 enabled. I don't see why we should keep this inconsistency (@taketwo any objections?). So yes, please enable it by default.

**Comment by taketwo** [comment]
No objections.

(Though in future I'd prefer to have `WITH_QT` to toggle Qt support in general, and something like `QT_VERSION`, which can be set to 4 or 5 to specify desired version.)

**Comment by severin-lemaignan** [comment]
I've updated the PR: let see what jenkins says...

**Comment by ToMadoRe** [comment]
retest this please

**Comment by ToMadoRe** [comment]
retest this please

**Pull request merged**
